src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\DBAL\Types\Types;

#[ORM\Entity(repositoryClass: ProductRepository::class)]

class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $productName = null;

    #[ORM\Column(length: 255)]
    private ?string $productDescription = null;

    #[ORM\Column]
    private ?int $productCount = null;

    #[ORM\Column]
    private ?float $productPrice = null;

    #[ORM\ManyToOne(inversedBy: 'productss')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'products')]
    private Collection $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $product_img = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $p_image_file = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): self
    {
        $this->productName = $productName;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->productDescription;
    }

    public function setProductDescription(string $productDescription): self
    {
        $this->productDescription = $productDescription;

        return $this;
    }

    public function getProductCount(): ?int
    {
        return $this->productCount;
    }

    public function setProductCount(int $productCount): self
    {
        $this->productCount = $productCount;

        return $this;
    }

    public function getProductPrice(): ?float
    {
        return $this->productPrice;
    }

    public function setProductPrice(float $productPrice): self
    {
        $this->productPrice = $productPrice;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addProduct($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeProduct($this);
        }

        return $this;
    }

    public function getProductImg(): ?string
    {
        return $this->product_img;
    }
    /**
     * @param string|null $product_img
    */
    public function setProductImg(?string $product_img): self
    {
        $this->product_img = $product_img;

        return $this;
    }

    public function getPImageFile(): ?File
    {
        return $this->p_image_file;
    }
    /**
     * @param File|null $p_image_file
    */
    public function setPImageFile(?File $p_image_file=null): self
    {
        $this->p_image_file = $p_image_file;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Session\Session;


class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart_page')]
    public function showAll(ProductRepository $productRepository): Response
    {
        $products = $productRepository;
        $products = $products->findBy(['id'=>1]);
        return $this->render('cart/index.html.twig', [
            'product' => $products,
        ]);
    } 

    #[Route('/cart/add', name: 'cart_add')]
    public function productAddSession(ProductRepository $productRepository , Request $request): Response
    {   
        $session = $this->get('session');

        if ($session->get('cart')) {
            $cart =  $session->get('cart');
        } else {
            $cart = [];
        }

        array_push($cart, $request->get('productId'));
        $session->set('cart', $cart);      
        return $this->redirect('/carts');
    } 

    #[Route('/carts', name: 'carts_page')]
    public function a(ProductRepository $productRepository , Request $request): Response
    {         
        $products=[];
        $session = $this->get('session'); 
        $i=0;
        foreach (array_count_values($session->get('cart'))  as $key => $value) {
            $product =$productRepository->findBy(['id'=>$key]);            
            array_push($products, $product[0]);           
            $products[$i]->quantity=$key;
            $i++;
        }
        $totalPrice=0.0;
        foreach($products as $product){
            $totalPrice = $totalPrice+$product->getProductPrice() * $product->quantity;
        } 
        return $this->render('cart/index.html.twig', [
            'product' => $products,
            'totalPrice'=>$totalPrice
        ]);     
    } 
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EnUygun E-Commerce{% endblock %}

{% block body %}

<div>
    <ul style="list-style-type: none; margin: 0; padding: 0;  overflow: hidden;">
        <li style="float: left;"><a href="/" style="display: block; padding:12px 14px; background-color: #27ae60;display: block; padding:12px 16px;background-color: #27ae60;color:white; text-decoration:none; ">Home Page</a></li>
        <li style="float: left;"><a href="/carts" style="display: block; padding:12px 14px; background-color: #27ae60;display: block; padding:12px 16px;background-color: #27ae60;color:white; text-decoration:none; ">Cart</a></li>
        <li style="float: left;"><a href="user_register" style="display: block; padding:12px 14px; background-color: #27ae60;display: block; padding:12px 16px;background-color: #27ae60;color:white; text-decoration:none; ">Register</a></li>
        <li style="float: left;"><a href="login" style="display: block; padding:12px 14px; background-color: #27ae60;display: block; padding:12px 16px;background-color: #27ae60;color:white; text-decoration:none;">Login</a></li>
        <li style="float: right;"><a href="buy?totalPrice={{ totalPrice}}" style="display: block; padding:12px 14px; background-color: #27ae60;display: block; padding:12px 16px;background-color: #27ae60;color:white; text-decoration:none;">Buy: Total Price: {{ totalPrice}} ₺</a></li>       
    </ul>
</div>

<center>
<div class="row" >
    {% for products in product %}
        <div class="card" style="width: 18rem; float: left; display: inline-block; "> 
            <div class="card-body" style="justify-content: space-between; border:1px solid black; margin:10px;">
                <img src="/assets/images/products/{{ products.productImg }}" class="card-img-top" alt="{{ products.productName }} width="200" height="200" >
                <h3 class="card-title">Name:{{ products.productName }} </h3>       
                <h5 class="card-title">Quantity:{{ products.quantity}} </h5>       
                <h5><p class="card-text">Description: {{ products.productDescription }}</p></h5>
                <h5><p class="card-text">Price: {{ products.productPrice }} ₺</p></h5>            
            </div>                    
        </div>       
    {% endfor %}
</div>
</center>
{% endblock %}